### ISSUE TITLE
Aluminum follow links block configuration weights not applied

### ISSUE THREAD

**Issue by amklose** [TopFloorTech/drupal-aluminum#1]
In the block configuration for the follow links, you can assign weights to each of the links, however the order of the links doesn't change depending on how you set the weight.

**Comment by bmcclure** [comment]
Just realized it wasn't taking into account the block settings at all for that block (oops!). Fixing this now.

**Comment by bmcclure** [comment]
@amklose This should be resolved in the latest 8.x-1.x release, but let me know if you still experience any issues
